
import "../globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "antd/dist/reset.css";
import SidebarWrapper from "@/components/layout/SidebarWrapper";

export const metadata = {
  title: "Blog Management System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
     
          <AntdRegistry>
            <SidebarWrapper>
              {children}
            </SidebarWrapper>
          </AntdRegistry>
      </body>
    </html>
  );
}
